function cern_simulator
    % CERN SIMULATOR GUI - Program z interfejsem graficznym do symulacji cząstek
    % Autor: Krzysztof Bezubik
    % Data: 2025-04-07

    % Tworzenie i konfiguracja głównego okna
    fig = figure('Name', 'pow pow pow krzysiu piontek', 'NumberTitle', 'off', ...
                'Position', [100, 100, 1000, 600], 'MenuBar', 'none', ...
                'Resize', 'on', 'CloseRequestFcn', @exitProgram);

    % Definicja kolorów interfejsu
    colors.background = [0.95, 0.95, 0.95];
    colors.panel = [0.9, 0.9, 0.9];
    colors.button = [0.85, 0.85, 0.85];
    colors.particle1 = [0.8, 0.2, 0.2]; % czerwony
    colors.particle2 = [0.2, 0.2, 0.8]; % niebieski

    % Ustawienie tła głównego okna
    set(fig, 'Color', colors.background);

    % Układ interfejsu - podział przestrzeni

    % Panel kontrolny (po lewej)
    controlPanel = uipanel('Parent', fig, ...
                         'Units', 'normalized', ...
                         'Position', [0.01, 0.01, 0.28, 0.98], ...
                         'Title', 'Panel kontrolny', ...
                         'BackgroundColor', colors.panel);

    % Panel symulacji (po prawej)
    simulationPanel = uipanel('Parent', fig, ...
                            'Units', 'normalized', ...
                            'Position', [0.30, 0.01, 0.69, 0.98], ...
                            'Title', 'Symulacja', ...
                            'BackgroundColor', colors.panel);

    % Umieszczenie osi do symulacji wewnątrz panelu symulacji
    simulationAxes = axes('Parent', simulationPanel, ...
                         'Units', 'normalized', ...
                         'Position', [0.05, 0.05, 0.9, 0.9], ...
                         'XLim', [-10, 10], 'YLim', [-10, 10], ...
                         'DataAspectRatio', [1 1 1], ...
                         'Box', 'on', 'XGrid', 'on', 'YGrid', 'on');
    title(simulationAxes, 'Symulacja ruchu cząstek');
    xlabel(simulationAxes, 'X');
    ylabel(simulationAxes, 'Y');

    % Konfiguracja elementów panelu kontrolnego (dzielimy na sekcje)
    % Panel cząstki 1
    p1Panel = uipanel('Parent', controlPanel, ...
                     'Units', 'normalized', ...
                     'Position', [0.05, 0.76, 0.9, 0.2], ...
                     'Title', 'Cząstka 1 (czerwona)', ...
                     'BackgroundColor', colors.panel);

    % Panel cząstki 2
    p2Panel = uipanel('Parent', controlPanel, ...
                     'Units', 'normalized', ...
                     'Position', [0.05, 0.52, 0.9, 0.2], ...
                     'Title', 'Cząstka 2 (niebieska)', ...
                     'BackgroundColor', colors.panel);

    % Panel przycisków sterujących
    controlButtonsPanel = uipanel('Parent', controlPanel, ...
                                'Units', 'normalized', ...
                                'Position', [0.05, 0.4, 0.9, 0.08], ...
                                'Title', 'Sterowanie', ...
                                'BackgroundColor', colors.panel);

    % Panel informacyjny
    infoPanel = uipanel('Parent', controlPanel, ...
                       'Units', 'normalized', ...
                       'Position', [0.05, 0.05, 0.9, 0.3], ...
                       'Title', 'Dane symulacji', ...
                       'BackgroundColor', colors.panel);

    % --- PANEL CZĄSTKI 1 ---

    % Etykiety i pola cząstki 1
    % Masa
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.8, 0.3, 0.15], ...
             'String', 'Masa:');
    p1MassEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                          'Units', 'normalized', ...
                          'Position', [0.4, 0.8, 0.5, 0.15], ...
                          'String', '1.0', ...
                          'BackgroundColor', 'white', ...
                          'Callback', @updateParticles);

    % Ładunek
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.65, 0.3, 0.15], ...
             'String', 'Ładunek:');
    p1ChargeEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                            'Units', 'normalized', ...
                            'Position', [0.4, 0.65, 0.5, 0.15], ...
                            'String', '-1.0', ...
                            'BackgroundColor', 'white', ...
                            'Callback', @updateParticles);

    % Prędkość X
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.5, 0.3, 0.15], ...
             'String', 'Prędkość X:');
    p1VelocityXEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.5, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Prędkość Y
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.35, 0.3, 0.15], ...
             'String', 'Prędkość Y:');
    p1VelocityYEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.35, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Pozycja X
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.2, 0.3, 0.15], ...
             'String', 'Pozycja X:');
    p1PositionXEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.2, 0.5, 0.15], ...
                               'String', '-5.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Pozycja Y
    uicontrol('Parent', p1Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.05, 0.3, 0.15], ...
             'String', 'Pozycja Y:');
    p1PositionYEdit = uicontrol('Parent', p1Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.05, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % --- PANEL CZĄSTKI 2 ---

    % Etykiety i pola cząstki 2
    % Masa
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.8, 0.3, 0.15], ...
             'String', 'Masa:');
    p2MassEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                          'Units', 'normalized', ...
                          'Position', [0.4, 0.8, 0.5, 0.15], ...
                          'String', '2.0', ...
                          'BackgroundColor', 'white', ...
                          'Callback', @updateParticles);

    % Ładunek
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.65, 0.3, 0.15], ...
             'String', 'Ładunek:');
    p2ChargeEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                            'Units', 'normalized', ...
                            'Position', [0.4, 0.65, 0.5, 0.15], ...
                            'String', '-1.0', ...
                            'BackgroundColor', 'white', ...
                            'Callback', @updateParticles);

    % Prędkość X
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.5, 0.3, 0.15], ...
             'String', 'Prędkość X:');
    p2VelocityXEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.5, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Prędkość Y
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.35, 0.3, 0.15], ...
             'String', 'Prędkość Y:');
    p2VelocityYEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.35, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Pozycja X
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.2, 0.3, 0.15], ...
             'String', 'Pozycja X:');
    p2PositionXEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.2, 0.5, 0.15], ...
                               'String', '5.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % Pozycja Y
    uicontrol('Parent', p2Panel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.05, 0.3, 0.15], ...
             'String', 'Pozycja Y:');
    p2PositionYEdit = uicontrol('Parent', p2Panel, 'Style', 'edit', ...
                               'Units', 'normalized', ...
                               'Position', [0.4, 0.05, 0.5, 0.15], ...
                               'String', '0.0', ...
                               'BackgroundColor', 'white', ...
                               'Callback', @updateParticles);

    % --- PANEL PRZYCISKÓW KONTROLNYCH ---

    % Przycisk Start
    startButton = uicontrol('Parent', controlButtonsPanel, ...
                           'Style', 'pushbutton', ...
                           'Units', 'normalized', ...
                           'Position', [0.05, 0.2, 0.25, 0.6], ...
                           'String', 'Start', ...
                           'Callback', @startSimulation, ...
                           'BackgroundColor', colors.button);

    % Przycisk Stop
    stopButton = uicontrol('Parent', controlButtonsPanel, ...
                          'Style', 'pushbutton', ...
                          'Units', 'normalized', ...
                          'Position', [0.375, 0.2, 0.25, 0.6], ...
                          'String', 'Stop', ...
                          'Callback', @stopSimulation, ...
                          'BackgroundColor', colors.button);

    % Przycisk Reset
    resetButton = uicontrol('Parent', controlButtonsPanel, ...
                           'Style', 'pushbutton', ...
                           'Units', 'normalized', ...
                           'Position', [0.7, 0.2, 0.25, 0.6], ...
                           'String', 'Reset', ...
                           'Callback', @resetSimulation, ...
                           'BackgroundColor', colors.button);

    % --- PANEL INFORMACYJNY ---

    % Siła Coulomba
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.85, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Siła Coulomba:');
    forceText = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                         'Units', 'normalized', ...
                         'Position', [0.45, 0.85, 0.5, 0.12], ...
                         'String', '0 N', ...
                         'HorizontalAlignment', 'left', ...
                         'BackgroundColor', 'white');

    % Energia kinetyczna cząstki 1
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.71, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Energia kinetyczna 1:');
    energy1Text = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                          'Units', 'normalized', ...
                          'Position', [0.45, 0.71, 0.5, 0.12], ...
                          'String', '0 J', ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', 'white');

    % Energia kinetyczna cząstki 2
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.57, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Energia kinetyczna 2:');
    energy2Text = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                          'Units', 'normalized', ...
                          'Position', [0.45, 0.57, 0.5, 0.12], ...
                          'String', '0 J', ...
                          'HorizontalAlignment', 'left', ...
                          'BackgroundColor', 'white');

    % Pęd cząstki 1
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.43, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Pęd 1 [x,y]:');
    momentum1Text = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                            'Units', 'normalized', ...
                            'Position', [0.45, 0.43, 0.5, 0.12], ...
                            'String', '[0, 0]', ...
                            'HorizontalAlignment', 'left', ...
                            'BackgroundColor', 'white');

    % Pęd cząstki 2
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.29, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Pęd 2 [x,y]:');
    momentum2Text = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                            'Units', 'normalized', ...
                            'Position', [0.45, 0.29, 0.5, 0.12], ...
                            'String', '[0, 0]', ...
                            'HorizontalAlignment', 'left', ...
                            'BackgroundColor', 'white');

    % Czas symulacji
    uicontrol('Parent', infoPanel, 'Style', 'text', ...
             'Units', 'normalized', ...
             'Position', [0.05, 0.15, 0.35, 0.12], ...
             'HorizontalAlignment', 'left', ...
             'String', 'Czas symulacji:');
    timeText = uicontrol('Parent', infoPanel, 'Style', 'text', ...
                        'Units', 'normalized', ...
                        'Position', [0.45, 0.15, 0.5, 0.12], ...
                        'String', '0 s', ...
                        'HorizontalAlignment', 'left', ...
                        'BackgroundColor', 'white');

    % --- ZMIENNE GLOBALNE dla funkcji ---
    simData = struct();
    simData.particle1 = createParticle(1.0, [-5, 0, 0], [0, 0, 0], 'p1', -1.0);
    simData.particle2 = createParticle(2.0, [5, 0, 0], [0, 0, 0], 'p2', -1.0);
    simData.isRunning = false;
    % Usunięto linię tworzącą obiekt timer
    simData.time = 0;
    simData.dt = 0.05;
    simData.historyLength = 20;
    simData.p1History = zeros(simData.historyLength, 2);
    simData.p2History = zeros(simData.historyLength, 2);

    % Inicjalizacja grafiki cząstek
    simData.p1Handle = plot(simulationAxes, simData.particle1.position(1), simData.particle1.position(2), ...
                         'o', 'MarkerSize', 10*simData.particle1.mass, ...
                         'MarkerFaceColor', colors.particle1, 'MarkerEdgeColor', 'none');
    simData.p2Handle = plot(simulationAxes, simData.particle2.position(1), simData.particle2.position(2), ...
                         'o', 'MarkerSize', 10*simData.particle2.mass, ...
                         'MarkerFaceColor', colors.particle2, 'MarkerEdgeColor', 'none');

    % Inicjalizacja trajektorii
    simData.p1TrajectoryHandle = plot(simulationAxes, NaN, NaN, '-', 'Color', [0.8, 0.2, 0.2, 0.5], 'LineWidth', 1);
    simData.p2TrajectoryHandle = plot(simulationAxes, NaN, NaN, '-', 'Color', [0.2, 0.2, 0.8, 0.5], 'LineWidth', 1);

    % Inicjalizacja wektorów sił i prędkości
    simData.p1VelocityHandle = quiver(simulationAxes, simData.particle1.position(1), simData.particle1.position(2), ...
                                  0, 0, 'r', 'LineWidth', 1);
    simData.p2VelocityHandle = quiver(simulationAxes, simData.particle2.position(1), simData.particle2.position(2), ...
                                  0, 0, 'b', 'LineWidth', 1);
    simData.p1ForceHandle = quiver(simulationAxes, simData.particle1.position(1), simData.particle1.position(2), ...
                                0, 0, 'm', 'LineWidth', 1);
    simData.p2ForceHandle = quiver(simulationAxes, simData.particle2.position(1), simData.particle2.position(2), ...
                                0, 0, 'c', 'LineWidth', 1);

    % Ustawienie typu interakcji (przyciąganie/odpychanie)
    simData.interactionTextHandle = text(0, 9, '', 'FontSize', 12, 'HorizontalAlignment', 'center', ...
                                       'Parent', simulationAxes);

    % Wywołanie funkcji inicjalizującej pozycje cząstek
    updateParticles();

    % ===== FUNKCJE POMOCNICZE =====

    % Funkcja tworząca cząstkę
    function particle = createParticle(mass, position, velocity, type, charge)
        particle = struct();
        particle.mass = mass;
        particle.position = position;
        particle.velocity = velocity;
        particle.type = type;
        particle.charge = charge;
    end

    % Funkcja obliczająca siłę elektrostatyczną między cząstkami
    function [F_vec, F_mag] = calculateElectricForce(p1, p2)
        % Stała Coulomba
        k = 8.99e9; % N*m^2/C^2

        % Wektor od p1 do p2
        r_vec = p2.position(1:2) - p1.position(1:2);
        r_vec(3) = 0; % Ignorujemy wymiar Z
        r_mag = norm(r_vec);

        % Unikamy dzielenia przez zero
        if r_mag < 1e-10
            F_vec = [0, 0, 0];
            F_mag = 0;
            return;
        end

        % Jednostkowy wektor kierunku
        r_unit = r_vec / r_mag;

        % Siła elektrostatyczna (wartość): F = k * (q1 * q2) / r^2
        F_mag = k * (p1.charge * p2.charge) / (r_mag^2);

        % Wektor siły: dodatni - przyciąganie, ujemny - odpychanie
        F_vec = F_mag * r_unit;
    end

    % Funkcja do aktualizacji parametrów cząstek z pól edycji
    function updateParticles(~, ~)
        % Odczytanie wartości z pól edycji
        try
            simData.particle1.mass = max(0.1, str2double(get(p1MassEdit, 'String')));
            simData.particle1.charge = str2double(get(p1ChargeEdit, 'String'));
            simData.particle1.velocity(1) = str2double(get(p1VelocityXEdit, 'String'));
            simData.particle1.velocity(2) = str2double(get(p1VelocityYEdit, 'String'));
            simData.particle1.position(1) = str2double(get(p1PositionXEdit, 'String'));
            simData.particle1.position(2) = str2double(get(p1PositionYEdit, 'String'));

            simData.particle2.mass = max(0.1, str2double(get(p2MassEdit, 'String')));
            simData.particle2.charge = str2double(get(p2ChargeEdit, 'String'));
            simData.particle2.velocity(1) = str2double(get(p2VelocityXEdit, 'String'));
            simData.particle2.velocity(2) = str2double(get(p2VelocityYEdit, 'String'));
            simData.particle2.position(1) = str2double(get(p2PositionXEdit, 'String'));
            simData.particle2.position(2) = str2double(get(p2PositionYEdit, 'String'));

            % Aktualizacja rozmiaru cząstek
            set(simData.p1Handle, 'MarkerSize', 10*simData.particle1.mass);
            set(simData.p2Handle, 'MarkerSize', 10*simData.particle2.mass);

            % Aktualizacja pozycji cząstek
            set(simData.p1Handle, 'XData', simData.particle1.position(1), ...
                                'YData', simData.particle1.position(2));
            set(simData.p2Handle, 'XData', simData.particle2.position(1), ...
                                'YData', simData.particle2.position(2));

            % Aktualizacja historii
            simData.p1History = zeros(simData.historyLength, 2);
            simData.p2History = zeros(simData.historyLength, 2);

            % Aktualizacja wektorów
            updateVelocityVectors();
            updateForceVectors();

            % Aktualizacja danych symulacji
            updateSimulationData();

            % Reset czasu symulacji
            simData.time = 0;
            set(timeText, 'String', sprintf('%.2f s', simData.time));

        catch
            errordlg('Podane wartości są nieprawidłowe!', 'Błąd');
        end
    end

    % Funkcja do aktualizacji wektorów prędkości
    function updateVelocityVectors()
        scale = 0.5; % Skala wizualizacji prędkości
        set(simData.p1VelocityHandle, 'XData', simData.particle1.position(1), ...
                                     'YData', simData.particle1.position(2), ...
                                     'UData', scale * simData.particle1.velocity(1), ...
                                     'VData', scale * simData.particle1.velocity(2));
        set(simData.p2VelocityHandle, 'XData', simData.particle2.position(1), ...
                                     'YData', simData.particle2.position(2), ...
                                     'UData', scale * simData.particle2.velocity(1), ...
                                     'VData', scale * simData.particle2.velocity(2));
    end

    % Funkcja do aktualizacji wektorów sił
    function updateForceVectors()
        % Obliczanie sił
        [F_2_on_1, F_mag] = calculateElectricForce(simData.particle1, simData.particle2);
        F_1_on_2 = -F_2_on_1; % Trzecia zasada dynamiki Newtona

        % Ustawienie skali wizualizacji sił
        scale = 0.01; % Skala do wizualizacji

        % Aktualizacja wektorów sił
        set(simData.p1ForceHandle, 'XData', simData.particle1.position(1), ...
                                 'YData', simData.particle1.position(2), ...
                                 'UData', scale * F_2_on_1(1), ...
                                 'VData', scale * F_2_on_1(2));
        set(simData.p2ForceHandle, 'XData', simData.particle2.position(1), ...
                                 'YData', simData.particle2.position(2), ...
                                 'UData', scale * F_1_on_2(1), ...
                                 'VData', scale * F_1_on_2(2));

        % Ustawienie typu interakcji
        if simData.particle1.charge * simData.particle2.charge > 0
            interaction_type = 'ODPYCHANIE';
            set(simData.interactionTextHandle, 'String', interaction_type, 'Color', 'red');
        elseif simData.particle1.charge * simData.particle2.charge < 0
            interaction_type = 'PRZYCIĄGANIE';
            set(simData.interactionTextHandle, 'String', interaction_type, 'Color', 'green');
        else
            interaction_type = 'BRAK INTERAKCJI';
            set(simData.interactionTextHandle, 'String', interaction_type, 'Color', 'black');
        end
    end

    % Funkcja do aktualizacji wyświetlanych danych symulacji
    function updateSimulationData()
        % Obliczanie sił
        [~, F_mag] = calculateElectricForce(simData.particle1, simData.particle2);

        % Obliczanie energii kinetycznych
        E1 = 0.5 * simData.particle1.mass * norm(simData.particle1.velocity)^2;
        E2 = 0.5 * simData.particle2.mass * norm(simData.particle2.velocity)^2;

        % Obliczanie pędów
        p1 = simData.particle1.mass * simData.particle1.velocity(1:2);
        p2 = simData.particle2.mass * simData.particle2.velocity(1:2);

        % Aktualizacja pól tekstowych
        set(forceText, 'String', sprintf('%.3e N', F_mag));
        set(energy1Text, 'String', sprintf('%.3e J', E1));
        set(energy2Text, 'String', sprintf('%.3e J', E2));
        set(momentum1Text, 'String', sprintf('[%.3f, %.3f]', p1(1), p1(2)));
        set(momentum2Text, 'String', sprintf('[%.3f, %.3f]', p2(1), p2(2)));
    end

% Funkcja do uruchamiania symulacji
function startSimulation(~, ~)
    if ~simData.isRunning
        simData.isRunning = true;
        % Uruchamiamy pętlę symulacji
        timerLoop();
    end
end

% Funkcja do zatrzymywania symulacji
function stopSimulation(~, ~)
    simData.isRunning = false;
    % Nie ma potrzeby wywoływać stop() na timerze
end

% Pętla symulująca timer
function timerLoop()
    while simData.isRunning
        % Wywołanie funkcji aktualizującej symulację
        updateSimulation();

        % Odświeżenie GUI
        drawnow;

        % Pauza dla lepszej wizualizacji
        pause(simData.dt); % odpowiednik Period w timerze
    end
end

    % Funkcja aktualizująca symulację (wywoływana przez timer)
    function updateSimulation(~, ~)
        % Aktualizacja czasu
        simData.time = simData.time + simData.dt;
        set(timeText, 'String', sprintf('%.2f s', simData.time));

        % Obliczanie sił i przyspieszeń
        [F_2_on_1, ~] = calculateElectricForce(simData.particle1, simData.particle2);
        F_1_on_2 = -F_2_on_1; % Trzecia zasada dynamiki Newtona

        % Obliczanie przyspieszeń
        a1 = F_2_on_1(1:2) / simData.particle1.mass;
        a1(3) = 0; % Zerujemy składową Z
        a2 = F_1_on_2(1:2) / simData.particle2.mass;
        a2(3) = 0; % Zerujemy składową Z

        % Aktualizacja prędkości
        simData.particle1.velocity(1:2) = simData.particle1.velocity(1:2) + a1(1:2) * simData.dt;
        simData.particle2.velocity(1:2) = simData.particle2.velocity(1:2) + a2(1:2) * simData.dt;

        % Aktualizacja pozycji
        simData.particle1.position(1:2) = simData.particle1.position(1:2) + simData.particle1.velocity(1:2) * simData.dt;
        simData.particle2.position(1:2) = simData.particle2.position(1:2) + simData.particle2.velocity(1:2) * simData.dt;

        % Sprawdzanie odbicia od ścian (idealne sprężyste odbicie)
        xlim = get(simulationAxes, 'XLim');
        ylim = get(simulationAxes, 'YLim');

        % Odbicie cząstki 1 od ścian
        if simData.particle1.position(1) - simData.particle1.mass < xlim(1)
            simData.particle1.position(1) = xlim(1) + simData.particle1.mass;
            simData.particle1.velocity(1) = -simData.particle1.velocity(1);
        elseif simData.particle1.position(1) + simData.particle1.mass > xlim(2)
            simData.particle1.position(1) = xlim(2) - simData.particle1.mass;
            simData.particle1.velocity(1) = -simData.particle1.velocity(1);
        end

        if simData.particle1.position(2) - simData.particle1.mass < ylim(1)
            simData.particle1.position(2) = ylim(1) + simData.particle1.mass;
            simData.particle1.velocity(2) = -simData.particle1.velocity(2);
        elseif simData.particle1.position(2) + simData.particle1.mass > ylim(2)
            simData.particle1.position(2) = ylim(2) - simData.particle1.mass;
            simData.particle1.velocity(2) = -simData.particle1.velocity(2);
        end

        % Odbicie cząstki 2 od ścian
        if simData.particle2.position(1) - simData.particle2.mass < xlim(1)
            simData.particle2.position(1) = xlim(1) + simData.particle2.mass;
            simData.particle2.velocity(1) = -simData.particle2.velocity(1);
        elseif simData.particle2.position(1) + simData.particle2.mass > xlim(2)
            simData.particle2.position(1) = xlim(2) - simData.particle2.mass;
            simData.particle2.velocity(1) = -simData.particle2.velocity(1);
        end

        if simData.particle2.position(2) - simData.particle2.mass < ylim(1)
            simData.particle2.position(2) = ylim(1) + simData.particle2.mass;
            simData.particle2.velocity(2) = -simData.particle2.velocity(2);
        elseif simData.particle2.position(2) + simData.particle2.mass > ylim(2)
            simData.particle2.position(2) = ylim(2) - simData.particle2.mass;
            simData.particle2.velocity(2) = -simData.particle2.velocity(2);
        end

        % Sprawdzanie kolizji między cząstkami
        distance = norm(simData.particle1.position(1:2) - simData.particle2.position(1:2));
        collision_threshold = simData.particle1.mass + simData.particle2.mass;

        if distance <= collision_threshold
            % Obsługa kolizji - prosty model odbicia sprężystego
            % (w pełnej implementacji należałoby użyć bardziej zaawansowanego modelu)

            % Wektor łączący środki cząstek
            r_vec = simData.particle2.position(1:2) - simData.particle1.position(1:2);
            r_unit = r_vec / norm(r_vec);

            % Składowe prędkości wzdłuż kierunku zderzenia
            v1_proj = dot(simData.particle1.velocity(1:2), r_unit);
            v2_proj = dot(simData.particle2.velocity(1:2), r_unit);

            % Obliczenie nowych prędkości (wymiana pędów)
            m1 = simData.particle1.mass;
            m2 = simData.particle2.mass;

            v1_new = ((m1 - m2) * v1_proj + 2 * m2 * v2_proj) / (m1 + m2);
            v2_new = ((m2 - m1) * v2_proj + 2 * m1 * v1_proj) / (m1 + m2);

            % Aktualizacja składowych prędkości wzdłuż kierunku zderzenia
            simData.particle1.velocity(1:2) = simData.particle1.velocity(1:2) + (v1_new - v1_proj) * r_unit;
            simData.particle2.velocity(1:2) = simData.particle2.velocity(1:2) + (v2_new - v2_proj) * r_unit;

            % Odsunięcie cząstek, aby uniknąć "przyklejania"
            overlap = collision_threshold - distance;
            simData.particle1.position(1:2) = simData.particle1.position(1:2) - 0.5 * overlap * r_unit;
            simData.particle2.position(1:2) = simData.particle2.position(1:2) + 0.5 * overlap * r_unit;
        end

        % Aktualizacja pozycji cząstek na rysunku
        set(simData.p1Handle, 'XData', simData.particle1.position(1), ...
                            'YData', simData.particle1.position(2));
        set(simData.p2Handle, 'XData', simData.particle2.position(1), ...
                            'YData', simData.particle2.position(2));

        % Aktualizacja historii pozycji dla trajektorii
        simData.p1History = [simData.particle1.position(1:2); simData.p1History(1:end-1,:)];
        simData.p2History = [simData.particle2.position(1:2); simData.p2History(1:end-1,:)];

        % Aktualizacja trajektorii
        set(simData.p1TrajectoryHandle, 'XData', simData.p1History(:,1), 'YData', simData.p1History(:,2));
        set(simData.p2TrajectoryHandle, 'XData', simData.p2History(:,1), 'YData', simData.p2History(:,2));

        % Aktualizacja wektorów
        updateVelocityVectors();
        updateForceVectors();

        % Aktualizacja danych symulacji
        updateSimulationData();

        % Aktualizacja pól edycji (opcjonalne)
        set(p1VelocityXEdit, 'String', sprintf('%.2f', simData.particle1.velocity(1)));
        set(p1VelocityYEdit, 'String', sprintf('%.2f', simData.particle1.velocity(2)));
        set(p1PositionXEdit, 'String', sprintf('%.2f', simData.particle1.position(1)));
        set(p1PositionYEdit, 'String', sprintf('%.2f', simData.particle1.position(2)));

        set(p2VelocityXEdit, 'String', sprintf('%.2f', simData.particle2.velocity(1)));
        set(p2VelocityYEdit, 'String', sprintf('%.2f', simData.particle2.velocity(2)));
        set(p2PositionXEdit, 'String', sprintf('%.2f', simData.particle2.position(1)));
        set(p2PositionYEdit, 'String', sprintf('%.2f', simData.particle2.position(2)));

        drawnow;
    end
    % Funkcja do zamknięcia programu
    function exitProgram(~, ~)
      % Zatrzymanie symulacji, jeśli działa
      if simData.isRunning
          simData.isRunning = false;
      end
    delete(gcf);
  end
end



