function openPlotConfig(~, ~)
    % Tworzenie okna dialogowego
    plotFig = figure('Name', 'dodawanie nowy wykres', ...
                     'Position', [200, 200, 200, 200], ...
                     'MenuBar', 'none', ...
                     'NumberTitle', 'off', ...
                     'Resize', 'off');
                 
    % Lista rozwijana dla osi X
    uicontrol('Parent', plotFig, 'Style', 'text', ...
              'Position', [20, 150, 80, 20], ...
              'String', 'Oś X:');
    xAxisMenu = uicontrol('Parent', plotFig, 'Style', 'popupmenu', ...
                          'Position', [100, 150, 150, 20], ...
                          'String', {'Czas', 'Energia kinetyczna 1', 'Energia kinetyczna 2', 'Pęd 1', 'Pęd 2', 'Siła coulomba'});
    
    % Lista rozwijana dla osi Y
    uicontrol('Parent', plotFig, 'Style', 'text', ...
              'Position', [20, 100, 80, 20], ...
              'String', 'Oś Y:');
    yAxisMenu = uicontrol('Parent', plotFig, 'Style', 'popupmenu', ...
                          'Position', [100, 100, 150, 20], ...
                          'String', {'Czas', 'Energia kinetyczna 1', 'Energia kinetyczna 2', 'pęd1', 'P3d 2', 'siła Culomba'});
    
    % Przycisk zatwierdzenia
    uicontrol('Parent', plotFig, 'Style', 'pushbutton', ...
              'Position', [100, 50, 100, 30], ...
              'String', 'Dodaj wykres', ...
              'Callback', @(~, ~) addPlot(xAxisMenu, yAxisMenu, plotFig));
end
