function wykresy(~, ~)
    % Tworzenie nowego okna dla panelu wykresów
    fig = figure('Name', 'generator wykresów ', ...
                 'NumberTitle', 'off', ...
                 'Position', [100, 100, 600, 400], ...
                 'MenuBar', 'none', ...
                 'ToolBar', 'none');

    % Panel wyboru danych
    dataPanel = uipanel('Parent', fig, ...
                        'Title', 'Wybór danych', ...
                        'Units', 'normalized', ...
                        'Position', [0.05, 0.55, 0.9, 0.4]);

    % Przykładowe dane (możesz zastąpić swoimi)
    data = struct('Czas', 1:100, ...
                  'energia kinetyczna', rand(1, 100), ...
                  'pęd1', sin(1:100), ...
                  'siła coulomba', cos(1:100));

    % Listy rozwijane do wyboru osi X i Y
    uicontrol('Parent', dataPanel, ...
              'Style', 'text', ...
              'String', 'Oś X:', ...
              'Units', 'normalized', ...
              'Position', [0.05, 0.7, 0.2, 0.2]);

    xAxisPopup = uicontrol('Parent', dataPanel, ...
                           'Style', 'popupmenu', ...
                           'String', fieldnames(data), ...
                           'Units', 'normalized', ...
                           'Position', [0.3, 0.75, 0.6, 0.2]);

    uicontrol('Parent', dataPanel, ...
              'Style', 'text', ...
              'String', 'Oś Y:', ...
              'Units', 'normalized', ...
              'Position', [0.05, 0.4, 0.2, 0.2]);

    yAxisPopup = uicontrol('Parent', dataPanel, ...
                           'Style', 'popupmenu', ...
                           'String', fieldnames(data), ...
                           'Units', 'normalized', ...
                           'Position', [0.3, 0.45, 0.6, 0.2]);

    % Przycisk do rysowania wykresu
    uicontrol('Parent', dataPanel, ...
              'Style', 'pushbutton', ...
              'String', 'Rysuj wykres', ...
              'Units', 'normalized', ...
              'Position', [0.35, 0.1, 0.3, 0.2], ...
              'Callback', @rysujWykres);

    % Oś wykresu
    ax = axes('Parent', fig, ...
              'Units', 'normalized', ...
              'Position', [0.1, 0.1, 0.8, 0.4]);

    % Funkcja rysująca wykres
    function rysujWykres(~, ~)
        % Pobranie wyboru użytkownika
        xField = fieldnames(data);
        yField = fieldnames(data);
        xData = data.(xField{xAxisPopup.Value});
        yData = data.(yField{yAxisPopup.Value});

        % Rysowanie wykresu
        plot(ax, xData, yData);
        xlabel(ax, xField{xAxisPopup.Value});
        ylabel(ax, yField{yAxisPopup.Value});
        title(ax, 'Wykres dynamiczny');
        grid(ax, 'on');
    end
end
